"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import environ


BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------
# ENV
# ---------------------------------------------------

env = environ.Env()

environ.Env.read_env(
    os.path.join(BASE_DIR, ".env")
)


# ---------------------------------------------------
# SECURITY
# ---------------------------------------------------

SECRET_KEY = env("SECRET_KEY")

DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["*"]
)



INSTALLED_APPS = [

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",

    "django_celery_results",

    "workflows",
    "reconciliation",
]



MIDDLEWARE = [

    "django.middleware.security.SecurityMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]




ROOT_URLCONF = "config.urls"


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [

                "django.template.context_processors.debug",

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ---------------------------------------------------
# WSGI
# ---------------------------------------------------

WSGI_APPLICATION = "config.wsgi.application"


DATABASES = {

    "default": {

        "ENGINE": "django.db.backends.postgresql",

        "NAME": env("POSTGRES_DB"),

        "USER": env("POSTGRES_USER"),

        "PASSWORD": env("POSTGRES_PASSWORD"),

        "HOST": env("POSTGRES_HOST"),

        "PORT": env("POSTGRES_PORT"),
    }
}


AUTH_PASSWORD_VALIDATORS = [

    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },

    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },

    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },

    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]



LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(
    BASE_DIR,
    "staticfiles"
)


MEDIA_URL = "/media/"

MEDIA_ROOT = os.path.join(
    BASE_DIR,
    "media"
)


# ---------------------------------------------------
# CELERY
# ---------------------------------------------------

CELERY_BROKER_URL = env(
    "CELERY_BROKER_URL"
)

CELERY_RESULT_BACKEND = env(
    "CELERY_RESULT_BACKEND"
)

CELERY_ACCEPT_CONTENT = [
    "application/json"
]

CELERY_TASK_SERIALIZER = "json"

CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = env(
    "TIME_ZONE",
    default="Asia/Kolkata"
)

CELERY_WORKER_MAX_TASKS_PER_CHILD = 50



DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)